<?php

declare(strict_types=1);

namespace Semitexa\Media;

use Semitexa\Core\Attribute\Capability;

/**
 * What this package offers, for the capability catalog.
 *
 * Without this the package is invisible to anyone whose project has not
 * installed it - which is precisely the audience worth telling, since they are
 * the ones about to build it by hand. The convention is one `Capabilities` class
 * per package: a definite place to look, and a definite place for a guard to
 * check.
 *
 * Nothing reads this at runtime.
 */
#[Capability(
    id: 'media.assets',
    summary: 'Image-first asset management: uploads, async derived variants, tenant quotas and delivery URLs.',
    useWhen: 'Users upload images that must be resized, cropped or served in several formats.',
    avoidWhen: 'You only need to keep bytes and hand them back unchanged - semitexa/storage does that without a variant pipeline.',
    replaces: [
        'an imagick resize in the upload handler, blocking the request on every image',
        'a naming convention for thumbnail paths, regenerated by a script when it drifts',
    ],
    seeAlso: 'semitexa/storage',
)]
final class Capabilities
{
}
